### PR TITLE
Upgrade the Ruby version to 2.1.5 as 1.9.3 is deprecated

### PR DESCRIPTION
**Pull request by issyl0**

### CODE REVIEW

**Comment by issyl0** [comment]
This doesn't appear to have branch builds enabled either.

In dev, after this change: `24 examples, 0 failures`.

**Comment by jamiecobbett** [comment]
In case you were unaware, Ruby version upgrades to applications require a manual restart of the application, otherwise the old version will continue to be used. That means this change will need some extra attention as it gets deployed to each environment

**Comment by issyl0** [comment]
People had pointed that out to me on PRs in other repos for the same thing earlier, but thanks. ISTR the plan is for @evilstreak and I to go through and do a big deploy tomorrow of all the Ruby upgrades (if I can fix all the tests in the failing ones...) - and Dom is aware of this extra step.

**Comment by jamiecobbett** [comment]
Tests also pass on my machine and 2.1.5 appears to be in production :+1:

**Pull request merged**
