### PR TITLE
Upgrade rails to fix secrity issues

### PR DESCRIPTION
**Pull request by dsingleton**

### CODE REVIEW

**Comment by boffbowsh** [comment]
Can we make Jenkins build this? The job exists but it doesn't appear to be configured correctly somewhere https://ci-new.alphagov.co.uk/view/Whitehall/job/govuk_business_support_api_branches/

**Comment by dsingleton** [comment]
@boffbowsh Yes, i'm in the middle of setting the job up.

**Comment by boffbowsh** [comment]
:+1:

**Comment by dsingleton** [comment]
I'll open a PR to add branch builds, once thats merged i'll rebase it in to this branch.

Closing in the mean time.

**Comment by dsingleton** [comment]
Now with Branch Builds ™

**Pull request merged**
