### PR TITLE
Return 404 for missing schemes and 410 for withdrawn ones

### PR DESCRIPTION
**Pull request by h-lame**
For: https://trello.com/c/bczvDiYg/355-fix-errors-on-withdrawn-schemes-in-business-support-api

We get a bunch of requests to this API for slugs that don't exist and these requests explode with a `NoMethodError` when they attempt to call `.to_hash` on the `nil` response from the content-api.  Instead we catch the `nil` response and render a 404.

### CODE REVIEW

**Comment by h-lame** [comment]
Note that the trello card suggested we return a `410` as a response.  I went with a `404` because it wasn't clear how to tell if a `nil` from the content-api is because the slug is for a withdrawn scheme or for a scheme that hasn't existed.

**Comment by davidbasalla** [comment]
Looks good to me, also regarding returning the 404, given that it's not possible tell if it should be a 404 or 410. :+1:  

Spotted some per Ruby 1.9 Hash notation but that's probably something for a later day when do a linting overhaul of the app.

**Comment by h-lame** [comment]
Had a look at how [frontend](https://github.com/alphagov/frontend) does it and found the [`artefact!`](https://github.com/alphagov/gds-api-adapters/blob/master/lib/gds_api/content_api.rb#L93-L95) method which doesn't swallow the exceptions meaning we *can* treat missing vs. withdrawn differently.

**Comment by brenetic** [comment]
:+1:

**Pull request merged**
